enviroments:
    '1 Host X 1 V100': 1
    '1 Host X 2 V100': 2
    '1 Host X 4 V100': 4
    '1 Host X 8 V100': 8
    # '2 Host X 8 V100': 16
    # '4 Host X 8 V100': 32
    # '8 Host X 8 V100': 64
    # '16 Host X 8 V100': 128

device:
    'TeslaV100'

platform:
    'pytorch'

baseline_path:
    'ai_simulator/simulator_benchmark/data/torch/baseline.json'

resource_pool_path:
    'ai_simulator/simulator_benchmark/data/resource_pool.yaml'

nccl_path:
    './'

tasks:
    bert_large_b16:
        model:
            'bert_large'
        type:
            'NLP'
        batch_size:
            16
        graph_path:
           'ai_simulator/simulator_benchmark/data/torch/graphs/bert_large_b16.json'
        graph_path_multi_gpu:
           'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/bert_large_b16.json'
        database_path:
           'ai_simulator/simulator_benchmark/data/torch/database/bert_large_b16_db.json'

    GPT2_b16:
        model:
            'gpt2'
        type:
            'NLP'
        batch_size:
            16
        graph_path:
           'ai_simulator/simulator_benchmark/data/torch/graphs/GPT2_b16.json'
        graph_path_multi_gpu:
           'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/GPT2_b16.json'
        database_path:
           'ai_simulator/simulator_benchmark/data/torch/database/GPT2_b16_db.json'

    vgg19_b256:
        model:
            'vgg19'
        type:
            'CV'
        batch_size:
            256
        graph_path:
           'ai_simulator/simulator_benchmark/data/torch/graphs/vgg19_b256.json'
        graph_path_multi_gpu:
           'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/vgg19_b256.json'
        database_path:
           'ai_simulator/simulator_benchmark/data/torch/database/vgg19_b256_db.json'

    resnet152_b128:
        model:
            'resnet152'
        type:
            'CV'
        batch_size:
            128
        graph_path:
            'ai_simulator/simulator_benchmark/data/torch/graphs/resnet152_b128.json'
        graph_path_multi_gpu:
            'ai_simulator/simulator_benchmark/data/torch/graphs/distributed/resnet152_b128.json'
        database_path:
            'ai_simulator/simulator_benchmark/data/torch/database/resnet152_b128_db.json'

